import { Item } from '../types';

export const ITEMS: Item[] = [
  // Poké Balls (Official)
  {
    id: 'poke-ball',
    name: 'Poké Ball',
    description: 'A device for catching wild Pokémon. It is thrown like a ball at a Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/poke-ball.png',
    type: 'ball',
    price: 200,
    catchRate: 1.0,
  },
  {
    id: 'great-ball',
    name: 'Great Ball',
    description: 'A good, high-performance Poké Ball that provides a higher Pokémon catch rate than a standard Poké Ball.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/great-ball.png',
    type: 'ball',
    price: 600,
    catchRate: 1.5,
  },
  {
    id: 'ultra-ball',
    name: 'Ultra Ball',
    description: 'An ultra-high-performance Poké Ball that provides a higher Pokémon catch rate than a Great Ball.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ultra-ball.png',
    type: 'ball',
    price: 1200,
    catchRate: 2.0,
  },
  {
    id: 'master-ball',
    name: 'Master Ball',
    description: 'The best Poké Ball with the ultimate level of performance. It will catch any wild Pokémon without fail.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/master-ball.png',
    type: 'ball',
    price: 50000,
    catchRate: 255, // Guaranteed catch
  },
  // Fan-made Poké Balls
  {
    id: 'shadow-ball',
    name: 'Shadow Ball',
    description: 'A mysterious ball that is more effective against Ghost and Dark-type Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dusk-ball.png', // Using dusk ball as placeholder
    type: 'ball',
    price: 2500,
    catchRate: 3.0,
  },
  {
    id: 'cosmic-ball',
    name: 'Cosmic Ball',
    description: 'A ball forged from star-dust. Highly effective against Legendary Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/luxury-ball.png', // Using luxury ball as placeholder
    type: 'ball',
    price: 10000,
    catchRate: 4.0,
  },
  {
    id: 'elite-ball',
    name: 'Elite Ball',
    description: 'The ultimate fan-made ball. It has a high catch rate and doubles the stats of the caught Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/cherish-ball.png', // Using cherish ball as placeholder
    type: 'ball',
    price: 25000,
    catchRate: 5.0,
  },
  // Healing Items
  {
    id: 'potion',
    name: 'Potion',
    description: 'A spray-type medicine for treating wounds. It can be used to restore 20 HP to a single Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/potion.png',
    type: 'healing',
    price: 300,
    healAmount: 20,
  },
  {
    id: 'super-potion',
    name: 'Super Potion',
    description: 'A spray-type medicine for treating wounds. It can be used to restore 60 HP to a single Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/super-potion.png',
    type: 'healing',
    price: 700,
    healAmount: 60,
  },
  // Materials
  {
    id: 'stardust',
    name: 'Stardust',
    description: 'Lovely, red-colored sand with a loose, silky feel. It can be sold at a high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/stardust.png',
    type: 'material',
    price: 1000,
  },
  {
    id: 'rare-candy',
    name: 'Rare Candy',
    description: 'A candy that is packed with energy. It raises the level of a single Pokémon by one.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rare-candy.png',
    type: 'special',
    price: 5000,
  },
  {
    id: 'elite-energy-core',
    name: 'Elite Energy Core',
    description: 'A powerful core that can be used to supercharge your Pokémon. Increases all stats by 50%.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/magnet.png',
    type: 'special',
    price: 100000,
  },
  {
    id: 'mewtwo-dna',
    name: 'Mewtwo DNA',
    description: 'A sample of Mewtwo DNA. Used to unlock the secrets of the Mewtwo Planet.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/helix-fossil.png',
    type: 'material',
    price: 500000,
  },
  {
    id: 'god-stone',
    name: 'God Stone',
    description: 'A stone said to be from the beginning of time. Grants the holder immense power.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sun-stone.png',
    type: 'special',
    price: 1000000,
  },
  // --- 50 NEW ITEMS ---
  // More Poké Balls
  {
    id: 'net-ball',
    name: 'Net Ball',
    description: 'A Poké Ball that is somewhat more effective against Water and Bug-type Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/net-ball.png',
    type: 'ball',
    price: 1000,
    catchRate: 3.5,
  },
  {
    id: 'dive-ball',
    name: 'Dive Ball',
    description: 'A Poké Ball that works better on Pokémon that live underwater.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dive-ball.png',
    type: 'ball',
    price: 1000,
    catchRate: 3.5,
  },
  {
    id: 'nest-ball',
    name: 'Nest Ball',
    description: 'A Poké Ball that works better on weaker Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/nest-ball.png',
    type: 'ball',
    price: 1000,
    catchRate: 3.0,
  },
  {
    id: 'repeat-ball',
    name: 'Repeat Ball',
    description: 'A Poké Ball that works better on Pokémon species you have caught before.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/repeat-ball.png',
    type: 'ball',
    price: 1000,
    catchRate: 3.0,
  },
  {
    id: 'timer-ball',
    name: 'Timer Ball',
    description: 'A Poké Ball that becomes more effective the more turns are taken in battle.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/timer-ball.png',
    type: 'ball',
    price: 1000,
    catchRate: 4.0,
  },
  {
    id: 'luxury-ball',
    name: 'Luxury Ball',
    description: 'A comfortable Poké Ball that makes a caught Pokémon quickly grow friendly.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/luxury-ball.png',
    type: 'ball',
    price: 3000,
    catchRate: 1.5,
  },
  {
    id: 'premier-ball',
    name: 'Premier Ball',
    description: 'A rare Poké Ball that has been made to commemorate an event of some sort.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/premier-ball.png',
    type: 'ball',
    price: 5000,
    catchRate: 1.0,
  },
  {
    id: 'dusk-ball',
    name: 'Dusk Ball',
    description: 'A Poké Ball that makes it easier to catch wild Pokémon at night or in caves.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dusk-ball.png',
    type: 'ball',
    price: 1500,
    catchRate: 3.5,
  },
  {
    id: 'heal-ball',
    name: 'Heal Ball',
    description: 'A remedial Poké Ball that restores the caught Pokémon\'s HP and status.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/heal-ball.png',
    type: 'ball',
    price: 1000,
    catchRate: 1.0,
  },
  {
    id: 'quick-ball',
    name: 'Quick Ball',
    description: 'A Poké Ball that provides a high catch rate if used at the start of a battle.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/quick-ball.png',
    type: 'ball',
    price: 2000,
    catchRate: 5.0,
  },
  // More Healing Items
  {
    id: 'hyper-potion',
    name: 'Hyper Potion',
    description: 'A spray-type medicine for treating wounds. It can be used to restore 120 HP.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hyper-potion.png',
    type: 'healing',
    price: 1500,
    healAmount: 120,
  },
  {
    id: 'max-potion',
    name: 'Max Potion',
    description: 'A spray-type medicine for treating wounds. It fully restores HP.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/max-potion.png',
    type: 'healing',
    price: 2500,
    healAmount: 999,
  },
  {
    id: 'full-restore',
    name: 'Full Restore',
    description: 'A medicine that fully restores HP and heals all status conditions.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/full-restore.png',
    type: 'healing',
    price: 3000,
    healAmount: 999,
  },
  {
    id: 'revive',
    name: 'Revive',
    description: 'A medicine that can be used to revive a fainted Pokémon and restore half its HP.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/revive.png',
    type: 'healing',
    price: 2000,
    healAmount: 50,
  },
  {
    id: 'max-revive',
    name: 'Max Revive',
    description: 'A medicine that can be used to revive a fainted Pokémon and fully restore its HP.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/max-revive.png',
    type: 'healing',
    price: 5000,
    healAmount: 999,
  },
  {
    id: 'fresh-water',
    name: 'Fresh Water',
    description: 'Water with high mineral content. It restores 30 HP.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fresh-water.png',
    type: 'healing',
    price: 200,
    healAmount: 30,
  },
  {
    id: 'soda-pop',
    name: 'Soda Pop',
    description: 'A highly carbonated soda drink. It restores 50 HP.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/soda-pop.png',
    type: 'healing',
    price: 300,
    healAmount: 50,
  },
  {
    id: 'lemonade',
    name: 'Lemonade',
    description: 'A very sweet drink. It restores 70 HP.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lemonade.png',
    type: 'healing',
    price: 400,
    healAmount: 70,
  },
  {
    id: 'moomoo-milk',
    name: 'Moomoo Milk',
    description: 'Highly nutritious milk. It restores 100 HP.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/moomoo-milk.png',
    type: 'healing',
    price: 600,
    healAmount: 100,
  },
  {
    id: 'energy-powder',
    name: 'Energy Powder',
    description: 'A very bitter medicine powder. It restores 50 HP.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/energy-powder.png',
    type: 'healing',
    price: 500,
    healAmount: 50,
  },
  // Battle Items
  {
    id: 'x-attack',
    name: 'X Attack',
    description: 'An item that sharply boosts the Attack stat of a Pokémon during a battle.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/x-attack.png',
    type: 'battle',
    price: 1000,
    statBoost: { stat: 'attack', amount: 20 },
  },
  {
    id: 'x-defense',
    name: 'X Defense',
    description: 'An item that sharply boosts the Defense stat of a Pokémon during a battle.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/x-defense.png',
    type: 'battle',
    price: 1000,
    statBoost: { stat: 'defense', amount: 20 },
  },
  {
    id: 'x-speed',
    name: 'X Speed',
    description: 'An item that sharply boosts the Speed stat of a Pokémon during a battle.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/x-speed.png',
    type: 'battle',
    price: 1000,
    statBoost: { stat: 'speed', amount: 20 },
  },
  {
    id: 'x-accuracy',
    name: 'X Accuracy',
    description: 'An item that sharply boosts the accuracy of a Pokémon during a battle.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/x-accuracy.png',
    type: 'battle',
    price: 1000,
  },
  {
    id: 'dire-hit',
    name: 'Dire Hit',
    description: 'An item that raises the critical-hit ratio of a Pokémon during a battle.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dire-hit.png',
    type: 'battle',
    price: 1500,
  },
  {
    id: 'guard-spec',
    name: 'Guard Spec.',
    description: 'An item that prevents stat reduction of a Pokémon during a battle.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/guard-spec.png',
    type: 'battle',
    price: 2000,
  },
  // Evolution Items
  {
    id: 'fire-stone',
    name: 'Fire Stone',
    description: 'A peculiar stone that can make certain species of Pokémon evolve. It has a fiery orange heart.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fire-stone.png',
    type: 'evolution',
    price: 3000,
  },
  {
    id: 'water-stone',
    name: 'Water Stone',
    description: 'A peculiar stone that can make certain species of Pokémon evolve. It is the clear blue of a deep pool.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/water-stone.png',
    type: 'evolution',
    price: 3000,
  },
  {
    id: 'thunder-stone',
    name: 'Thunder Stone',
    description: 'A peculiar stone that can make certain species of Pokémon evolve. It has a distinct thunderbolt pattern.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/thunder-stone.png',
    type: 'evolution',
    price: 3000,
  },
  {
    id: 'leaf-stone',
    name: 'Leaf Stone',
    description: 'A peculiar stone that can make certain species of Pokémon evolve. It has a leaf pattern.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/leaf-stone.png',
    type: 'evolution',
    price: 3000,
  },
  {
    id: 'moon-stone',
    name: 'Moon Stone',
    description: 'A peculiar stone that can make certain species of Pokémon evolve. It is as black as the night sky.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/moon-stone.png',
    type: 'evolution',
    price: 5000,
  },
  {
    id: 'sun-stone',
    name: 'Sun Stone',
    description: 'A peculiar stone that can make certain species of Pokémon evolve. It is as red as the evening sun.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sun-stone.png',
    type: 'evolution',
    price: 5000,
  },
  {
    id: 'shiny-stone',
    name: 'Shiny Stone',
    description: 'A peculiar stone that can make certain species of Pokémon evolve. It shines with a dazzling light.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/shiny-stone.png',
    type: 'evolution',
    price: 6000,
  },
  {
    id: 'dusk-stone',
    name: 'Dusk Stone',
    description: 'A peculiar stone that can make certain species of Pokémon evolve. It is as dark as a moonless night.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dusk-stone.png',
    type: 'evolution',
    price: 6000,
  },
  {
    id: 'dawn-stone',
    name: 'Dawn Stone',
    description: 'A peculiar stone that can make certain species of Pokémon evolve. It sparkles like a glittering eye.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dawn-stone.png',
    type: 'evolution',
    price: 6000,
  },
  {
    id: 'ice-stone',
    name: 'Ice Stone',
    description: 'A peculiar stone that can make certain species of Pokémon evolve. It has a snowflake pattern.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ice-stone.png',
    type: 'evolution',
    price: 6000,
  },
  {
    id: 'mega-stone',
    name: 'Mega Stone',
    description: 'A mysterious stone that can trigger Mega Evolution in certain Pokémon during battle or permanently in this simulator.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mega-stone.png',
    type: 'evolution',
    price: 50000,
  },
  {
    id: 'trading-link',
    name: 'Trading Link',
    description: 'A digital link cable that simulates a trade, triggering evolution in Pokémon that normally require trading.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/link-cable.png',
    type: 'evolution',
    price: 15000,
  },
  // Materials & Treasures
  {
    id: 'nugget',
    name: 'Nugget',
    description: 'A nugget of pure gold that gives off a lustrous gleam. It can be sold at a high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/nugget.png',
    type: 'material',
    price: 5000,
  },
  {
    id: 'big-nugget',
    name: 'Big Nugget',
    description: 'A big nugget of pure gold that gives off a lustrous gleam. It can be sold at a very high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/big-nugget.png',
    type: 'material',
    price: 20000,
  },
  {
    id: 'pearl',
    name: 'Pearl',
    description: 'A somewhat small pearl that sparkles in a pretty silver color. It can be sold at a low price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pearl.png',
    type: 'material',
    price: 1000,
  },
  {
    id: 'big-pearl',
    name: 'Big Pearl',
    description: 'A quite large pearl that sparkles in a pretty silver color. It can be sold at a high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/big-pearl.png',
    type: 'material',
    price: 4000,
  },
  {
    id: 'star-piece',
    name: 'Star Piece',
    description: 'A small shard of a beautiful gem that sparkles in a red color. It can be sold at a high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/star-piece.png',
    type: 'material',
    price: 6000,
  },
  {
    id: 'comet-shard',
    name: 'Comet Shard',
    description: 'A shard of a comet that fell to the ground. It can be sold at a very high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/comet-shard.png',
    type: 'material',
    price: 30000,
  },
  // Elite & Special Items
  {
    id: 'omega-orb',
    name: 'Omega Orb',
    description: 'An orb pulsating with cosmic energy. It permanently boosts a Pokémon\'s HP by 100.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/orb.png',
    type: 'elite',
    price: 250000,
    statBoost: { stat: 'hp', amount: 100, isPermanent: true },
  },
  {
    id: 'alpha-core',
    name: 'Alpha Core',
    description: 'A core containing the essence of creation. It permanently boosts a Pokémon\'s Attack by 50.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/core.png',
    type: 'elite',
    price: 250000,
    statBoost: { stat: 'attack', amount: 50, isPermanent: true },
  },
  {
    id: 'titan-shield',
    name: 'Titan Shield',
    description: 'A shield forged from indestructible alloys. It permanently boosts a Pokémon\'s Defense by 50.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/shield.png',
    type: 'elite',
    price: 250000,
    statBoost: { stat: 'defense', amount: 50, isPermanent: true },
  },
  {
    id: 'sonic-wing',
    name: 'Sonic Wing',
    description: 'A wing that allows for movement beyond the speed of sound. It permanently boosts a Pokémon\'s Speed by 50.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/wing.png',
    type: 'elite',
    price: 250000,
    statBoost: { stat: 'speed', amount: 50, isPermanent: true },
  },
  {
    id: 'god-elixir',
    name: 'God Elixir',
    description: 'A legendary elixir that fully restores HP and grants a temporary 100% boost to all stats.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/elixir.png',
    type: 'elite',
    price: 500000,
    healAmount: 999,
  },
  {
    id: 'master-scroll',
    name: 'Maximum Scroll',
    description: 'A scroll containing the wisdom of ancient masters. It allows a Pokémon to learn any move of your choice.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/scroll.png',
    type: 'elite',
    price: 750000,
  },
  {
    id: 'infinity-gauntlet',
    name: 'Infinity Gauntlet',
    description: 'A gauntlet that grants the power of the four stones. Massively boosts all attack damage.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/gauntlet.png',
    type: 'elite',
    price: 5000000,
  },
  {
    id: 'mew-feather',
    name: 'Mew Feather',
    description: 'A feather from the mythical Pokémon Mew. It glows with a soft pink light.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/feather.png',
    type: 'special',
    price: 100000,
  },
  // --- 50 MORE ITEMS (Batch 2) ---
  // Specialized Poké Balls
  {
    id: 'friend-ball',
    name: 'Friend Ball',
    description: 'A Poké Ball that makes a caught Pokémon quickly grow friendly.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/friend-ball.png',
    type: 'ball',
    price: 1500,
    catchRate: 1.0,
  },
  {
    id: 'love-ball',
    name: 'Love Ball',
    description: 'A Poké Ball that works best on Pokémon of the opposite gender.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/love-ball.png',
    type: 'ball',
    price: 1500,
    catchRate: 8.0,
  },
  {
    id: 'lure-ball',
    name: 'Lure Ball',
    description: 'A Poké Ball that is good for catching Pokémon hooked by a Rod.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lure-ball.png',
    type: 'ball',
    price: 1500,
    catchRate: 4.0,
  },
  {
    id: 'moon-ball-catch',
    name: 'Moon Ball',
    description: 'A Poké Ball that is good for catching Pokémon that evolve using a Moon Stone.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/moon-ball.png',
    type: 'ball',
    price: 1500,
    catchRate: 4.0,
  },
  {
    id: 'fast-ball',
    name: 'Fast Ball',
    description: 'A Poké Ball that makes it easier to catch Pokémon which are quick to run away.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fast-ball.png',
    type: 'ball',
    price: 1500,
    catchRate: 4.0,
  },
  {
    id: 'heavy-ball',
    name: 'Heavy Ball',
    description: 'A Poké Ball that is better for catching very heavy Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/heavy-ball.png',
    type: 'ball',
    price: 1500,
    catchRate: 1.0,
  },
  {
    id: 'level-ball',
    name: 'Level Ball',
    description: 'A Poké Ball that works better on Pokémon that are a lower level than your own.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/level-ball.png',
    type: 'ball',
    price: 1500,
    catchRate: 1.0,
  },
  {
    id: 'sport-ball',
    name: 'Sport Ball',
    description: 'A special Poké Ball that is used during the Bug-Catching Contest.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sport-ball.png',
    type: 'ball',
    price: 2000,
    catchRate: 1.5,
  },
  {
    id: 'safari-ball',
    name: 'Safari Ball',
    description: 'A special Poké Ball that is used only in the Great Marsh and the Safari Zone.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/safari-ball.png',
    type: 'ball',
    price: 2000,
    catchRate: 1.5,
  },
  {
    id: 'park-ball',
    name: 'Park Ball',
    description: 'A special Poké Ball that is used during the Pal Park\'s Catching Show.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/park-ball.png',
    type: 'ball',
    price: 5000,
    catchRate: 255,
  },
  // Status Healing Items
  {
    id: 'antidote',
    name: 'Antidote',
    description: 'A spray-type medicine for treating poisoning. It can be used to lift the effects of being poisoned.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/antidote.png',
    type: 'healing',
    price: 100,
  },
  {
    id: 'paralyze-heal',
    name: 'Parlyz Heal',
    description: 'A spray-type medicine for treating paralysis. It can be used to lift the effects of paralysis.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/paralyze-heal.png',
    type: 'healing',
    price: 200,
  },
  {
    id: 'awakening',
    name: 'Awakening',
    description: 'A spray-type medicine for waking up Pokémon from sleep. It can be used to wake a sleeping Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/awakening.png',
    type: 'healing',
    price: 250,
  },
  {
    id: 'burn-heal',
    name: 'Burn Heal',
    description: 'A spray-type medicine for treating burns. It can be used to heal a Pokémon from a burn.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/burn-heal.png',
    type: 'healing',
    price: 250,
  },
  {
    id: 'ice-heal',
    name: 'Ice Heal',
    description: 'A spray-type medicine for treating freezing. It can be used to thaw a frozen Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ice-heal.png',
    type: 'healing',
    price: 250,
  },
  {
    id: 'full-heal',
    name: 'Full Heal',
    description: 'A spray-type medicine that heals all status conditions of a single Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/full-heal.png',
    type: 'healing',
    price: 600,
  },
  {
    id: 'lava-cookie',
    name: 'Lava Cookie',
    description: 'A local specialty of Lavaridge Town. It heals all status conditions.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lava-cookie.png',
    type: 'healing',
    price: 500,
  },
  {
    id: 'old-gateau',
    name: 'Old Gateau',
    description: 'A local specialty of the Old Chateau. It heals all status conditions.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/old-gateau.png',
    type: 'healing',
    price: 500,
  },
  {
    id: 'casteliacone',
    name: 'Casteliacone',
    description: 'A local specialty of Castelia City. It heals all status conditions.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/casteliacone.png',
    type: 'healing',
    price: 500,
  },
  {
    id: 'lumiose-galette',
    name: 'Lumiose Galette',
    description: 'A local specialty of Lumiose City. It heals all status conditions.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lumiose-galette.png',
    type: 'healing',
    price: 500,
  },
  // More Battle Items
  {
    id: 'x-sp-atk',
    name: 'X Sp. Atk',
    description: 'An item that sharply boosts the Sp. Atk stat of a Pokémon during a battle.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/x-special.png',
    type: 'battle',
    price: 1000,
    statBoost: { stat: 'attack', amount: 20 }, // Simplified to attack for now
  },
  {
    id: 'x-sp-def',
    name: 'X Sp. Def',
    description: 'An item that sharply boosts the Sp. Def stat of a Pokémon during a battle.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/x-special-defense.png',
    type: 'battle',
    price: 1000,
    statBoost: { stat: 'defense', amount: 20 }, // Simplified to defense for now
  },
  {
    id: 'focus-band',
    name: 'Focus Band',
    description: 'An item to be held by a Pokémon. It may allow the Pokémon to evade fainting.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/focus-band.png',
    type: 'battle',
    price: 5000,
  },
  {
    id: 'focus-sash',
    name: 'Focus Sash',
    description: 'An item to be held by a Pokémon. If it has full HP, it will endure a potential OHKO.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/focus-sash.png',
    type: 'battle',
    price: 10000,
  },
  {
    id: 'choice-band',
    name: 'Choice Band',
    description: 'An item to be held by a Pokémon. It boosts Attack but allows only one move.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/choice-band.png',
    type: 'battle',
    price: 15000,
    statBoost: { stat: 'attack', amount: 50 },
  },
  {
    id: 'choice-specs',
    name: 'Choice Specs',
    description: 'An item to be held by a Pokémon. It boosts Sp. Atk but allows only one move.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/choice-specs.png',
    type: 'battle',
    price: 15000,
    statBoost: { stat: 'attack', amount: 50 },
  },
  {
    id: 'choice-scarf',
    name: 'Choice Scarf',
    description: 'An item to be held by a Pokémon. It boosts Speed but allows only one move.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/choice-scarf.png',
    type: 'battle',
    price: 15000,
    statBoost: { stat: 'speed', amount: 50 },
  },
  {
    id: 'life-orb',
    name: 'Life Orb',
    description: 'An item to be held by a Pokémon. It boosts moves but drains HP each turn.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/life-orb.png',
    type: 'battle',
    price: 20000,
    statBoost: { stat: 'attack', amount: 30 },
  },
  {
    id: 'rocky-helmet',
    name: 'Rocky Helmet',
    description: 'An item to be held by a Pokémon. It damages attackers that make contact.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rocky-helmet.png',
    type: 'battle',
    price: 12000,
  },
  {
    id: 'assault-vest',
    name: 'Assault Vest',
    description: 'An item to be held by a Pokémon. It boosts Sp. Def but prevents status moves.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/assault-vest.png',
    type: 'battle',
    price: 15000,
    statBoost: { stat: 'defense', amount: 40 },
  },
  // More Evolution Items
  {
    id: 'protector',
    name: 'Protector',
    description: 'A protective item that makes Rhydon evolve when traded.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/protector.png',
    type: 'evolution',
    price: 8000,
  },
  {
    id: 'electirizer',
    name: 'Electirizer',
    description: 'A box packed with electric energy. It makes Electabuzz evolve.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/electirizer.png',
    type: 'evolution',
    price: 8000,
  },
  {
    id: 'magmarizer',
    name: 'Magmarizer',
    description: 'A box packed with magma energy. It makes Magmar evolve.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/magmarizer.png',
    type: 'evolution',
    price: 8000,
  },
  {
    id: 'dubious-disc',
    name: 'Dubious Disc',
    description: 'A transparent device overflowing with dubious data. It makes Porygon2 evolve.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dubious-disc.png',
    type: 'evolution',
    price: 10000,
  },
  {
    id: 'upgrade',
    name: 'Upgrade',
    description: 'A transparent device filled with data. It makes Porygon evolve.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/upgrade.png',
    type: 'evolution',
    price: 8000,
  },
  {
    id: 'reaper-cloth',
    name: 'Reaper Cloth',
    description: 'A cloth imbued with spiritual energy. It makes Dusclops evolve.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/reaper-cloth.png',
    type: 'evolution',
    price: 8000,
  },
  {
    id: 'dragon-scale',
    name: 'Dragon Scale',
    description: 'A thick and tough scale. It makes Seadra evolve.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dragon-scale.png',
    type: 'evolution',
    price: 8000,
  },
  {
    id: 'kings-rock',
    name: 'King\'s Rock',
    description: 'An item that may cause the opponent to flinch. It makes Slowpoke evolve.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/kings-rock.png',
    type: 'evolution',
    price: 8000,
  },
  {
    id: 'metal-coat',
    name: 'Metal Coat',
    description: 'A special metallic film that boosts Steel-type moves. It makes Onix evolve.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/metal-coat.png',
    type: 'evolution',
    price: 8000,
  },
  {
    id: 'prism-scale',
    name: 'Prism Scale',
    description: 'A mysterious scale that shines in rainbow colors. It makes Feebas evolve.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/prism-scale.png',
    type: 'evolution',
    price: 10000,
  },
  // More Treasures
  {
    id: 'tiny-mushroom',
    name: 'Tiny Mushroom',
    description: 'A small and rare mushroom. It can be sold at a low price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tiny-mushroom.png',
    type: 'material',
    price: 500,
  },
  {
    id: 'big-mushroom',
    name: 'Big Mushroom',
    description: 'A large and rare mushroom. It can be sold at a high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/big-mushroom.png',
    type: 'material',
    price: 2500,
  },
  {
    id: 'balm-mushroom',
    name: 'Balm Mushroom',
    description: 'A rare mushroom that gives off a nice fragrance. It can be sold at a very high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/balm-mushroom.png',
    type: 'material',
    price: 15000,
  },
  {
    id: 'relic-copper',
    name: 'Relic Copper',
    description: 'A copper coin used in an ancient civilization. It can be sold at a low price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/relic-copper.png',
    type: 'material',
    price: 1000,
  },
  {
    id: 'relic-silver',
    name: 'Relic Silver',
    description: 'A silver coin used in an ancient civilization. It can be sold at a high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/relic-silver.png',
    type: 'material',
    price: 5000,
  },
  {
    id: 'relic-gold',
    name: 'Relic Gold',
    description: 'A gold coin used in an ancient civilization. It can be sold at a very high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/relic-gold.png',
    type: 'material',
    price: 10000,
  },
  {
    id: 'relic-vase',
    name: 'Relic Vase',
    description: 'A vase used in an ancient civilization. It can be sold at a high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/relic-vase.png',
    type: 'material',
    price: 50000,
  },
  {
    id: 'relic-band',
    name: 'Relic Band',
    description: 'A band used in an ancient civilization. It can be sold at a high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/relic-band.png',
    type: 'material',
    price: 100000,
  },
  {
    id: 'relic-statue',
    name: 'Relic Statue',
    description: 'A statue used in an ancient civilization. It can be sold at a very high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/relic-statue.png',
    type: 'material',
    price: 200000,
  },
  {
    id: 'relic-crown',
    name: 'Relic Crown',
    description: 'A crown used in an ancient civilization. It can be sold at an extremely high price.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/relic-crown.png',
    type: 'material',
    price: 1000000,
  },
];
