import { Planet } from '../types';

export const PLANETS: Planet[] = [
  {
    id: 'earth-grasslands',
    name: 'Earth: Grasslands',
    description: 'A peaceful meadow where common Pokémon roam.',
    image: 'https://picsum.photos/seed/grass/400/400',
    color: '#2d5a27',
    unlockCost: 0,
    rarityMultiplier: 1.0,
    backgroundClass: 'bg-[#2d5a27]',
    grassClass: 'bg-[#1e3d1a]'
  },
  {
    id: 'earth-core',
    name: 'Core of the Earth',
    description: 'The molten center of our world. Extremely hot and dangerous.',
    image: 'https://picsum.photos/seed/lava/400/400',
    color: '#ff4500',
    unlockCost: 5000,
    rarityMultiplier: 2.5,
    backgroundClass: 'bg-gradient-to-br from-red-900 to-orange-600',
    grassClass: 'bg-orange-900/40'
  },
  {
    id: 'moon-base',
    name: 'Moon Base Alpha',
    description: 'Low gravity and mysterious craters. Home to lunar Pokémon.',
    image: 'https://picsum.photos/seed/moon/400/400',
    color: '#a0a0a0',
    unlockCost: 10000,
    rarityMultiplier: 3.0,
    backgroundClass: 'bg-[#1a1a1a]',
    grassClass: 'bg-gray-700/40'
  },
  {
    id: 'mars-desert',
    name: 'Mars: Red Desert',
    description: 'A dusty, crimson wasteland with hidden secrets.',
    image: 'https://picsum.photos/seed/mars/400/400',
    color: '#8b0000',
    unlockCost: 15000,
    rarityMultiplier: 3.5,
    backgroundClass: 'bg-[#8b0000]',
    grassClass: 'bg-red-900/40'
  },
  {
    id: 'jupiter-storms',
    name: 'Jupiter: Great Red Spot',
    description: 'A massive storm that has raged for centuries.',
    image: 'https://picsum.photos/seed/jupiter/400/400',
    color: '#d2691e',
    unlockCost: 20000,
    rarityMultiplier: 4.0,
    backgroundClass: 'bg-gradient-to-br from-orange-800 to-yellow-600',
    grassClass: 'bg-yellow-900/40'
  },
  {
    id: 'saturn-rings',
    name: 'Saturn: Ring City',
    description: 'Floating cities built within the icy rings of Saturn.',
    image: 'https://picsum.photos/seed/saturn/400/400',
    color: '#f4a460',
    unlockCost: 25000,
    rarityMultiplier: 4.5,
    backgroundClass: 'bg-[#f4a460]',
    grassClass: 'bg-orange-800/40'
  },
  {
    id: 'uranus-ice',
    name: 'Uranus: Frozen Tundra',
    description: 'An icy giant with freezing temperatures.',
    image: 'https://picsum.photos/seed/uranus/400/400',
    color: '#add8e6',
    unlockCost: 30000,
    rarityMultiplier: 5.0,
    backgroundClass: 'bg-[#add8e6]',
    grassClass: 'bg-blue-900/40'
  },
  {
    id: 'neptune-ocean',
    name: 'Neptune: Deep Abyss',
    description: 'A dark, watery world with crushing pressure.',
    image: 'https://picsum.photos/seed/neptune/400/400',
    color: '#00008b',
    unlockCost: 35000,
    rarityMultiplier: 5.5,
    backgroundClass: 'bg-[#00008b]',
    grassClass: 'bg-blue-950/40'
  },
  {
    id: 'pluto-outpost',
    name: 'Pluto: Edge of Sol',
    description: 'The furthest reaches of our solar system.',
    image: 'https://picsum.photos/seed/pluto/400/400',
    color: '#4b0082',
    unlockCost: 40000,
    rarityMultiplier: 6.0,
    backgroundClass: 'bg-[#4b0082]',
    grassClass: 'bg-purple-900/40'
  },
  {
    id: 'mewtwo-planet',
    name: 'Planet Mewtwo',
    description: 'A bio-engineered world. Home to the legendary Ultra Mewtwo.',
    image: 'https://picsum.photos/seed/mewtwo/400/400',
    color: '#800080',
    unlockCost: 100000,
    rarityMultiplier: 10.0,
    specialPokemon: ['mewtwo', 'mew'],
    backgroundClass: 'bg-gradient-to-br from-purple-900 via-indigo-950 to-black',
    grassClass: 'bg-purple-500/20'
  },
  {
    id: 'baby-mew-nest',
    name: "Baby Mew's Nest",
    description: 'A hidden, floating island where Baby Mews are born. Extremely rare.',
    image: 'https://picsum.photos/seed/babymew/400/400',
    color: '#ffb6c1',
    unlockCost: 250000,
    rarityMultiplier: 20.0,
    specialPokemon: ['mew'],
    backgroundClass: 'bg-gradient-to-br from-pink-200 via-white to-pink-100',
    grassClass: 'bg-pink-400/30'
  },
  {
    id: 'andromeda-nebula',
    name: 'Andromeda: Star Nursery',
    description: 'Where stars are born. Radiant and full of energy.',
    image: 'https://picsum.photos/seed/nebula/400/400',
    color: '#ff00ff',
    unlockCost: 50000,
    rarityMultiplier: 6.5,
    backgroundClass: 'bg-gradient-to-br from-pink-900 to-purple-800',
    grassClass: 'bg-pink-500/20'
  },
  {
    id: 'black-hole-edge',
    name: 'Event Horizon',
    description: 'The edge of a black hole where time stands still.',
    image: 'https://picsum.photos/seed/blackhole/400/400',
    color: '#000000',
    unlockCost: 60000,
    rarityMultiplier: 7.0,
    backgroundClass: 'bg-black',
    grassClass: 'bg-white/5'
  },
  {
    id: 'crystal-planet',
    name: 'Caelum: Crystal World',
    description: 'A planet made entirely of shimmering crystals.',
    image: 'https://picsum.photos/seed/crystal/400/400',
    color: '#00ffff',
    unlockCost: 70000,
    rarityMultiplier: 7.5,
    backgroundClass: 'bg-gradient-to-br from-cyan-900 to-blue-800',
    grassClass: 'bg-cyan-400/30'
  },
  {
    id: 'gold-planet',
    name: 'Aurum: Golden World',
    description: 'A world where everything is made of pure gold.',
    image: 'https://picsum.photos/seed/gold/400/400',
    color: '#ffd700',
    unlockCost: 80000,
    rarityMultiplier: 8.0,
    backgroundClass: 'bg-gradient-to-br from-yellow-700 to-yellow-500',
    grassClass: 'bg-yellow-900/40'
  },
  {
    id: 'diamond-star',
    name: 'Adamant: Diamond Star',
    description: 'A star that has cooled into a giant diamond.',
    image: 'https://picsum.photos/seed/diamond/400/400',
    color: '#ffffff',
    unlockCost: 90000,
    rarityMultiplier: 8.5,
    backgroundClass: 'bg-gradient-to-br from-slate-200 to-white',
    grassClass: 'bg-blue-200/40'
  },
  {
    id: 'void-dimension',
    name: 'The Void',
    description: 'A dimension between worlds. Nothingness and everything.',
    image: 'https://picsum.photos/seed/void/400/400',
    color: '#191970',
    unlockCost: 110000,
    rarityMultiplier: 9.0,
    backgroundClass: 'bg-[#191970]',
    grassClass: 'bg-black/40'
  },
  {
    id: 'cyber-world',
    name: 'Neon: Cyber World',
    description: 'A digital world made of code and light.',
    image: 'https://picsum.photos/seed/cyber/400/400',
    color: '#39ff14',
    unlockCost: 120000,
    rarityMultiplier: 9.5,
    backgroundClass: 'bg-black',
    grassClass: 'bg-green-500/20 shadow-[0_0_10px_#39ff14]'
  },
  {
    id: 'ancient-ruins',
    name: 'Archaic: Ancient Ruins',
    description: 'Ruins of a civilization that existed before time.',
    image: 'https://picsum.photos/seed/ruins/400/400',
    color: '#8b4513',
    unlockCost: 130000,
    rarityMultiplier: 10.5,
    backgroundClass: 'bg-[#8b4513]',
    grassClass: 'bg-yellow-950/40'
  },
  {
    id: 'spirit-realm',
    name: 'Ethereal: Spirit Realm',
    description: 'A world of ghosts and spirits.',
    image: 'https://picsum.photos/seed/spirit/400/400',
    color: '#e6e6fa',
    unlockCost: 140000,
    rarityMultiplier: 11.0,
    backgroundClass: 'bg-gradient-to-br from-indigo-900 to-purple-900',
    grassClass: 'bg-white/10'
  },
  {
    id: 'dragon-peak',
    name: 'Draco: Dragon Peak',
    description: 'High mountains where dragons rule the skies.',
    image: 'https://picsum.photos/seed/dragon/400/400',
    color: '#ff0000',
    unlockCost: 150000,
    rarityMultiplier: 12.0,
    backgroundClass: 'bg-gradient-to-br from-red-950 to-red-800',
    grassClass: 'bg-orange-600/20'
  },
  {
    id: 'omega-point',
    name: 'The Omega Point',
    description: 'The final destination of the universe.',
    image: 'https://picsum.photos/seed/omega/400/400',
    color: '#ffffff',
    unlockCost: 200000,
    rarityMultiplier: 15.0,
    backgroundClass: 'bg-white',
    grassClass: 'bg-black/5'
  },
  {
    id: 'shadow-realm',
    name: 'Umbra: Shadow Realm',
    description: 'A world where light is forbidden.',
    image: 'https://picsum.photos/seed/shadow/400/400',
    color: '#2f4f4f',
    unlockCost: 160000,
    rarityMultiplier: 12.5,
    backgroundClass: 'bg-black',
    grassClass: 'bg-gray-900/40'
  },
  {
    id: 'sky-kingdom',
    name: 'Aether: Sky Kingdom',
    description: 'Cities floating above the clouds.',
    image: 'https://picsum.photos/seed/sky/400/400',
    color: '#87ceeb',
    unlockCost: 170000,
    rarityMultiplier: 13.0,
    backgroundClass: 'bg-gradient-to-b from-blue-400 to-blue-200',
    grassClass: 'bg-white/30'
  },
  {
    id: 'magma-chamber',
    name: 'Ignis: Magma Chamber',
    description: 'A world of constant volcanic eruptions.',
    image: 'https://picsum.photos/seed/volcano/400/400',
    color: '#ff4500',
    unlockCost: 180000,
    rarityMultiplier: 13.5,
    backgroundClass: 'bg-gradient-to-br from-red-900 to-orange-700',
    grassClass: 'bg-orange-950/40'
  },
  {
    id: 'ocean-trench',
    name: 'Mariana: Ocean Trench',
    description: 'The deepest part of the cosmic ocean.',
    image: 'https://picsum.photos/seed/trench/400/400',
    color: '#000080',
    unlockCost: 190000,
    rarityMultiplier: 14.0,
    backgroundClass: 'bg-gradient-to-b from-blue-900 to-black',
    grassClass: 'bg-blue-950/60'
  },
  {
    id: 'time-rift',
    name: 'Chronos: Time Rift',
    description: 'A place where past, present, and future collide.',
    image: 'https://picsum.photos/seed/time/400/400',
    color: '#ffd700',
    unlockCost: 220000,
    rarityMultiplier: 16.0,
    backgroundClass: 'bg-gradient-to-br from-yellow-900 via-black to-yellow-900',
    grassClass: 'bg-yellow-400/10'
  },
  {
    id: 'dream-scape',
    name: 'Somnium: Dream Scape',
    description: 'A world made of pure imagination.',
    image: 'https://picsum.photos/seed/dream/400/400',
    color: '#ff69b4',
    unlockCost: 230000,
    rarityMultiplier: 17.0,
    backgroundClass: 'bg-gradient-to-br from-pink-400 via-purple-400 to-indigo-400',
    grassClass: 'bg-white/20'
  },
  {
    id: 'nightmare-realm',
    name: 'Phobia: Nightmare Realm',
    description: 'Where your deepest fears come to life.',
    image: 'https://picsum.photos/seed/nightmare/400/400',
    color: '#4b0082',
    unlockCost: 240000,
    rarityMultiplier: 18.0,
    backgroundClass: 'bg-gradient-to-br from-purple-950 to-black',
    grassClass: 'bg-red-950/40'
  }
];
